# Generated by Django 2.1.2 on 2018-10-30 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 30, 8, 31, 49, 831142))),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
